[package]
name = "compress_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flate2 = "1.0.20"
rust-lzma = "0.5.1"
rmw-utf8 = {path="../rmw-utf8"}
zstd = "0.9.0"
